### ISSUE TITLE
Unused templates, functions, global variables/parameters might not be an error (when the xsl is a library)

### ISSUE THREAD

**Issue by innovimax** [mricaud/xslt-quality#10]

**Comment by mricaud** [comment]
A new parameter `xslt-quality_xslt-is-a-library` can be added in the conf at stylesheet level to indicate if the stylesheet is a library or not. Depending on this value unused template/function/variable/parameters won't raise any error.

See [src\test\sample-lib.xsl](https://github.com/mricaud/xslt-quality/blob/master/src/test/sample-lib.xsl) for an example
