### ISSUE TITLE
Using template named "xsl:initial-template" results in warning

### ISSUE THREAD

**Issue by bmix** [mricaud/xslt-quality#24]
XLS-T 3.0 allows a transform to be run without an input document, when it contains a template named 'xsl:initial-template'.

This template gets called explicitly from outside of the stylesheet, via the processor's command line, therefore the warning, "[xslqual] Named template in unused the stylesheet", is redundant.

**Comment by mricaud** [comment]
Hi @bmix 
Thank you for the report, adding an exception here looks quite fair. I'm just wondering about "xsl:" prefix in the name of the mode. I guess it should also work if I write "XXX:initial-template" where XXX prefix references the XSLT ? Or maybe it is a reserved mode name ?

At the moment we are working on a new version of xslt-quality to let it more customizable.
This is almost finished. To avoid merge conflict, I guess we will first deliver this new version and then be able to go back to this issue.

**Comment by mricaud** [comment]
Correction OK.
Will be in next zip distribution (not yet)
(zip can be simply generated with the command `mvn install` from source)
