### ISSUE TITLE
validation problem with XSLT3

### ISSUE THREAD

**Issue by wondergarance** [mricaud/xslt-quality#3]
Hello,

I have a problem of validation the XSLT3 files with your schematron.
In a XSLT3, I declare some variables and functions and I call them between { }. The infomations in { } are not recognized by the schematron.
The error message is as follows:
[xslqual] Stylesheet function is unused

Qian

**Comment by mricaud** [comment]
Thank you Qian for this report. 

You're right, XSLT3 Text Value Template are not parsed by the schematron, which may report wrong errors like you had. This is also true with the rule #useSelectWhenPossible for example.

I guess some rules will need 2 "modes" XSLT2 and XSLT3 (maybe XSLT1) so we can have possible alternatives in the common rules.

I'll take a look to this as soon as possible.

**Comment by mricaud** [comment]
Hi @wondergarance , this should be OK now.
It was not easy to match TVT and AVT correctly, I also took into account namespace prefixes (that might change during xslt parsing).
For this reasons I need to use XSLT 3.0 querybinding in the schematron and embed xslt functions within the schematron.
Please have a look at the new instructions in the [README](https://github.com/mricaud/xslt-quality) to customize Oxygen properly.
Let me know if everything is alright for you.
Cheers
Matthieu
