### ISSUE TITLE
Add Schematron QuickFix

### ISSUE THREAD

**Issue by innovimax** [mricaud/xslt-quality#5]
http://www.schematron-quickfix.com/quickFix/guide.html

**Comment by mricaud** [comment]
Check @arithmeticus work and integrate it to the main branch

**Comment by mricaud** [comment]
2 SQF has been added on `xslt-quality_use-select-attribute-when-possible` and `xslt-quality_typing-with-as-attribute`
I close this issue for now thought other SQF might be added in the future
